spring.application.name=scm2.0
server.port=8081

# Activate dev profile
spring.profiles.active=dev

#mysql database configurarions
#datasource url


# 5. Hibernate settings (Ye table apne aap banane mein madad karta hai)
#important for creating tables automatically based on your entities
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.format_sql=true
spring.output.ansi.enabled=ALWAYS

scm.manager.upload-dir=https://static.vecteezy.com/system/resources/previews/005/544/718/original/profile-icon-design-free-vector.jpg


# Let Tomcat accept up to 20MB without crashing the connection
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB


# Externalized configurarions
app.base-url=http://localhost:8081

# Set Spring Security logging to INFO (hides DEBUG spam)
logging.level.org.springframework.security=off
logging.level.org.springframework.web=off


#security configuration
# spring.security.user.name=arun
# spring.security.user.password=arun

