spring.application.name=scm2.0
server.port=8081

# Activate dev profile
spring.profiles.active=dev

#mysql database configurarions
#datasource url


# 5. Hibernate settings (Ye table apne aap banane mein madad karta hai)
#important for creating tables automatically based on your entities
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.format_sql=true
spring.output.ansi.enabled=ALWAYS

scm.manager.upload-dir=https://static.vecteezy.com/system/resources/previews/005/544/718/original/profile-icon-design-free-vector.jpg






#security configuration
# spring.security.user.name=arun
# spring.security.user.password=arun

